root = "."

[build]
  cmd = "cd backend && go build -o /app/tmp/dmrmap ."
  bin = "./tmp/dmrmap"
  include_ext = ["go"]
  include_dir = ["backend"]
  exclude_dir = ["tmp", "frontend"]
  delay = 500

[misc]
  clean_on_exit = true
