root = "."

[build]
  cmd = "go build -o ./tmp/dmrmap ."
  bin = "./tmp/dmrmap"
  include_ext = ["go"]
  exclude_dir = ["tmp", "static", "data", "migrations"]
  delay = 500

[misc]
  clean_on_exit = true
