services:
  dmrmap:
    build: .
    tmpfs:
      - /app/data
    environment:
      - DB_PATH=/app/data/repeaters.db
      - JSON_PATH=/app/rptrs.json
      - LISTEN_ADDR=:8080
    restart: unless-stopped
