FROM golang:1.25-alpine
RUN apk add --no-cache nodejs npm
RUN go install github.com/air-verse/air@latest
RUN wget -qO /usr/local/share/talkgroups.json https://api.brandmeister.network/v2/talkgroup
WORKDIR /app
CMD cp -n /usr/local/share/talkgroups.json frontend/static/talkgroups.json 2>/dev/null; \
    cd frontend && npm install --silent && npm run watch & \
    air
